<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite" duration-ms="61" started-at="2016-11-15T23:56:56Z" finished-at="2016-11-15T23:56:56Z">
    <groups>
    </groups>
    <test name="sample test suite" duration-ms="61" started-at="2016-11-15T23:56:56Z" finished-at="2016-11-15T23:56:56Z">
      <class name="test.practice.string.RemoveOccurenceTest">
        <test-method status="PASS" signature="testBuiltInFunction()[pri:0, instance:test.practice.string.RemoveOccurenceTest@c9046b1]" name="testBuiltInFunction" duration-ms="22" started-at="2016-11-15T15:56:56Z" finished-at="2016-11-15T15:56:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBuiltInFunction -->
        <test-method status="PASS" signature="testInvalidInputs()[pri:0, instance:test.practice.string.RemoveOccurenceTest@c9046b1]" name="testInvalidInputs" duration-ms="2" started-at="2016-11-15T15:56:56Z" finished-at="2016-11-15T15:56:56Z">
          <exception class="java.lang.IllegalArgumentException">
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException
	at com.practice.string.RemoveOccurences.builtInFunction(RemoveOccurences.java:66)
	at test.practice.string.RemoveOccurenceTest.testInvalidInputs(RemoveOccurenceTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidInputs -->
        <test-method status="PASS" signature="testIterativeApproach()[pri:0, instance:test.practice.string.RemoveOccurenceTest@c9046b1]" name="testIterativeApproach" duration-ms="2" started-at="2016-11-15T15:56:56Z" finished-at="2016-11-15T15:56:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIterativeApproach -->
      </class> <!-- test.practice.string.RemoveOccurenceTest -->
    </test> <!-- sample test suite -->
  </suite> <!-- TestSuite -->
</testng-results>
